<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="husky">
  <!-- IMU Link -->
  <xacro:arg name="imu_xyz"     default="0 -0.15 0.075"/>
  <xacro:arg name="imu_rpy"     default="3.1415926 0 0"/>
  <xacro:arg name="imu_parent"  default="base_link"/>

  <!-- Realsense Camera Primary and Secondary -->
  <!-- <xacro:arg name="realsense_enabled"             default="$(optenv HUSKY_REALSENSE_ENABLED 1)" />
  <xacro:arg name="realsense_model"               default="$(optenv HUSKY_REALSENSE_MODEL d435)"/>
  <xacro:arg name="realsense_topic"               default="$(optenv HUSKY_REALSENSE_TOPIC realsense)" />
  <xacro:arg name="realsense_prefix"              default="$(optenv HUSKY_REALSENSE_PREFIX camera)" />
  <xacro:arg name="realsense_parent"              default="$(optenv HUSKY_REALSENSE_PARENT top_plate_link)" />
  <xacro:arg name="realsense_xyz"                 default="$(optenv HUSKY_REALSENSE_XYZ 0 0 0.3)" />
  <xacro:arg name="realsense_rpy"                 default="$(optenv HUSKY_REALSENSE_RPY 0 0 0)" />
  <xacro:property name="realsense_model"          value="$(arg realsense_model)"/> -->

  <!-- Bumper Extension -->
  <xacro:property name="husky_front_bumper_extend"  value="0" />
  <xacro:property name="husky_rear_bumper_extend"   value="0" />

  <!-- Height of the sensor arch in mm.  Must be either 510 or 300 -->
  <!-- <xacro:arg name="sensor_arch"         default="$(optenv HUSKY_SENSOR_ARCH 1)" />
  <xacro:arg name="sensor_arch_height"  default="$(optenv HUSKY_SENSOR_ARCH_HEIGHT 300)" />
  <xacro:arg name="sensor_arch_xyz"     default="$(optenv HUSKY_SENSOR_ARCH_OFFSET 0 0 0)"/>
  <xacro:arg name="sensor_arch_rpy"     default="$(optenv HUSKY_SENSOR_ARCH_RPY 0 0 0)"/> -->

  <!-- Extras -->
  <xacro:arg name="robot_namespace" default="/" />

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find husky_panda_realsense)/urdf/decorations.urdf.xacro" />
  <xacro:include filename="$(find armlab_description)/urdf/wheel.urdf.xacro" />
  <!-- <xacro:include filename="$(find project)/urdf/accessories/intel_realsense.urdf.xacro"/>
  <xacro:include filename="$(find project)/urdf/accessories/sensor_arch.urdf.xacro"/> -->

  
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.98740000" />
  <xacro:property name="base_y_size" value="0.57090000" />
  <xacro:property name="base_z_size" value="0.24750000" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.5120" />
  <xacro:property name="track" value="0.5708" />
  <xacro:property name="wheel_vertical_offset" value="0.03282" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.1143" />
  <xacro:property name="wheel_radius" value="0.1651" />

  <!-- Base link is the center of the robot's bottom plate -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://armlab_description/meshes/visual/base_link.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${( husky_front_bumper_extend - husky_rear_bumper_extend ) / 2.0} 0 ${base_z_size/4}" rpy="0 0 0" />
      <geometry>
        <box size="${ base_x_size + husky_front_bumper_extend + husky_rear_bumper_extend } ${base_y_size} ${base_z_size/2}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
      </geometry>
    </collision>
  </link>

  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!-- Inertial link stores the robot's inertial information -->
  <link name="inertial_link">
    <inertial>
      <mass value="146.034" />
      <origin xyz="-0.00065 -0.085 0.062" />
      <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <!-- Husky wheel macros -->
  <xacro:husky_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>

  <!-- Husky Decorations -->
  <xacro:husky_decorate />
  

  <!--
    Add the main sensor arch if the user has specifically enabled it, or if a sensor
    requires it for mounting
  -->
  <!-- <xacro:if value="$(arg sensor_arch)">
    <xacro:sensor_arch prefix="" parent="top_plate_link" size="$(arg sensor_arch_height)">
      <origin xyz="$(arg sensor_arch_xyz)" rpy="$(arg sensor_arch_rpy)"/>
    </xacro:sensor_arch>
  </xacro:if> -->

  <!--
      IMU Link: Standard location to add an IMU (i.e. UM7 or Microstrain)
  -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <origin xyz="$(arg imu_xyz)" rpy="$(arg imu_rpy)" />
    <parent link="$(arg imu_parent)" />
    <child link="imu_link" />
  </joint>
  <gazebo reference="imu_link">
  </gazebo>

  <!-- Intel Realsense Primary and Secondary -->
  <!-- <xacro:property name="realsense_enabled" value="$(arg realsense_enabled)"/>
  <xacro:property name="realsense_secondary_enabled" value="$(arg realsense_secondary_enabled)"/>
  <xacro:if value="${realsense_enabled or realsense_secondary_enabled}">
      <xacro:if value="${realsense_model == 'd435'}">
        <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
      </xacro:if>
      <xacro:if value="${realsense_model == 'd435i'}">
        <xacro:include filename="$(find realsense2_description)/urdf/_d435i.urdf.xacro" />
      </xacro:if>
      <xacro:if value="${realsense_model == 'd415'}">
        <xacro:include filename="$(find realsense2_description)/urdf/_d415.urdf.xacro" />
      </xacro:if>
      <xacro:if value="${realsense_model == 'd455'}">
        <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
      </xacro:if>
  </xacro:if>

  <xacro:if value="$(arg realsense_enabled)">
    <xacro:realsense_sensor rs_model="$(arg realsense_model)"
                            prefix="$(arg realsense_prefix)"
                            parent="$(arg realsense_parent)"
                            topic="$(arg realsense_topic)"
                            include="0">
      <origin xyz="$(arg realsense_xyz)" rpy="$(arg realsense_rpy)"/>
    </xacro:realsense_sensor>
  </xacro:if> -->

</robot>
